In [1]:
import numpy as np

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.


In [4]:
exp1 = np.arange(0,30,)
exp1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
exp1.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [12]:
exp2=np.random.randint(8,80,60)
exp2

array([17, 42, 38, 40, 67, 34, 71, 57, 29, 66, 59, 56, 21, 15, 23, 10, 41,
       30, 67, 23, 14, 18, 24, 39, 29, 24, 28, 41, 59, 61, 20, 70, 34, 30,
       14, 23, 40, 27, 47, 31, 59, 49, 70, 78, 27, 48, 27, 44, 10, 68, 13,
       17, 50, 48, 16, 46, 75, 53, 64, 49])

In [19]:
exp2.reshape(3,4,5)

array([[[17, 42, 38, 40, 67],
        [34, 71, 57, 29, 66],
        [59, 56, 21, 15, 23],
        [10, 41, 30, 67, 23]],

       [[14, 18, 24, 39, 29],
        [24, 28, 41, 59, 61],
        [20, 70, 34, 30, 14],
        [23, 40, 27, 47, 31]],

       [[59, 49, 70, 78, 27],
        [48, 27, 44, 10, 68],
        [13, 17, 50, 48, 16],
        [46, 75, 53, 64, 49]]])

In [20]:
exp2.reshape(3,4,5).shape

(3, 4, 5)

In [21]:
exp2.reshape(3,4,5).ndim

3

3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.



In [25]:
exp3=np.random.randint(0,10,(4,5))
exp3

array([[3, 4, 5, 2, 5],
       [7, 3, 3, 1, 2],
       [3, 9, 7, 9, 1],
       [6, 4, 6, 4, 6]])

In [29]:
exp3.reshape(20)

array([3, 4, 5, 2, 5, 7, 3, 3, 1, 2, 3, 9, 7, 9, 1, 6, 4, 6, 4, 6])

In [30]:
exp3.reshape(20).ndim

1

In [32]:
exp3.reshape(20).shape

(20,)

4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.


In [48]:
exp4=np.array([[2,5,1,3,140,40,4,9]]).reshape(2,4)
exp4

array([[  2,   5,   1,   3],
       [140,  40,   4,   9]])

In [50]:
for i in exp4:
  for m in i:
    print(m)

2
5
1
3
140
40
4
9


In [51]:
for x in np.nditer(exp4):
  print(x)

2
5
1
3
140
40
4
9


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.


In [54]:
exp5=np.array([5,10,15,20,25,30])
exp6=np.array([[1,2,3,4,5,6]])
 


In [56]:
exp5+exp6

array([[ 4,  8, 12, 16, 20, 24]])

In [60]:
exp5*exp6

array([[  5,  20,  45,  80, 125, 180]])

In [59]:
exp5/exp6


array([[5., 5., 5., 5., 5., 5.]])

In [57]:
exp5-exp6

array([[ 4,  8, 12, 16, 20, 24]])

6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [62]:
exp7=np.random.randint(0,100,10)
exp7

array([96, 81, 79,  1, 27, 38, 17, 98, 94, 42])

In [64]:
exp7.sum()

573

In [65]:
exp7.mean()

57.3

In [66]:
exp7.max()

98

In [67]:
exp7.var()

1185.21

In [68]:
exp7.std()

34.426879033685296

7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [71]:
exp8=np.arange(0,20)
exp8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
exp9=np.arange(500,531)
exp9

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [77]:
print(np.concatenate([exp8,exp9]))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515
 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530]


8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.


In [79]:
exp10=np.arange(15,51)
exp11=np.arange(10,101)

In [80]:
exp12=np.concatenate([exp10,exp11])
exp12

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [82]:
exp12[25:51]=888
exp12

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [87]:
exp13=np.arange(0,40,).reshape(8,5)
exp13

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [90]:
exp14=np.arange(320,360).reshape(8,5)
exp14

array([[320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [91]:
np.concatenate([exp13,exp14], axis=0)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [92]:
np.concatenate([exp13,exp14], axis=1)

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.


In [93]:
np.concatenate([exp13,exp14], axis=2) # hata veriyor

AxisError: ignored

In [97]:
np.stack([exp13,exp14], axis=2)

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.


In [98]:
exp15=np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] )

In [100]:
np.where(exp15==5)

(array([ 5, 13]),)

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.


In [107]:
np.where(exp15 % 2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.


In [108]:
np.where(exp15 > 4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


---



In [109]:
np.where(exp15%5==0)

(array([ 1,  2,  5, 13]),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin


In [110]:
np.random.randint(85,101,1)

array([92])

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.


In [113]:
np.random.randint(1,24,9).reshape(3,3)

array([[ 9,  1,  7],
       [ 8, 20, 16],
       [ 3, 22, 20]])

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.


In [118]:
exp16=np.arange(35,60)

In [119]:
np.random.choice(exp16)

39

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.


In [165]:
np.random.choice([3,8,10,53], (2,5))


array([[53, 10,  8, 53,  8],
       [53, 10, 53,  3,  8]])

In [162]:
exp19=np.random.choice([3, 8, 10, 53], size=(2, 5))
print(exp19)

[[53 10 53 53 53]
 [53  3  8  3 10]]
